# Adapted from https://github.com/zeebe-io/benchmark-helm/blob/main/charts/zeebe-benchmark/values-realistic-benchmark.yaml
zeebe:
  config:
    zeebe.broker.exporters.job-metric.className: "com.github.sijoma.exporter.JobMetricExporter"
    zeebe.broker.exporters.job-metric.jarPath: "/usr/local/zeebe/exporters/job-metric-exporter.jar"

camunda-platform:
  enabled: true

  zeebe:
    image:
      repository: camunda/zeebe
      tag: 8.6.0
    pvcStorageClassName: "standard"

    retention:
      enabled: true
      minimumAge: 1d

    resources:
      limits:
        cpu: 1350m
        memory: 1Gi
      requests:
        cpu: 1350m
        memory: 1Gi



    initContainers:
      - name: job-metric-exporter
        image: ghcr.io/sijoma/camunda-autoscaling-hackday/job-metric-exporter:autoscaling-demo
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: zeebe-exporters
            mountPath: /exporters

    # Since Helm would override the values of `extraVolumes` specified in the benchmark-helm, we need to copy them
    extraVolumes:
      - name: benchmark-config
        configMap:
          name: benchmark-config
          defaultMode: 0754
      - name: zeebe-exporters
        emptyDir: {}

    # Since Helm would override the values of `extraVolumeMounts` specified in the benchmark-helm, we need to copy them
    extraVolumeMounts:
      - name: benchmark-config
        mountPath: /usr/local/zeebe/config/benchmark-config.yaml
        subPath: benchmark-config.yaml
      - name: zeebe-exporters
        mountPath: /usr/local/zeebe/exporters

  zeebeGateway:
    replicas: 1

    image:
      repository: camunda/zeebe
      tag: 8.6.0

    resources:
      limits:
        cpu: 450m
        memory: 1Gi
      requests:
        cpu: 450m
        memory: 1Gi

  elasticsearch:
    enabled: true
    imageTag: 8.9.2

    master:
      fullnameOverride: elastic
      nameOverride: elastic
      replicaCount: 1
      heapSize: 3g
      resources:
        requests:
          cpu: 1
          memory: 3Gi
        limits:
          cpu: 2
          memory: 6Gi
      persistence:
        storageClass: "standard"
        size: 10Gi
        accessModes: [ "ReadWriteOnce" ]
