workers:
  # Disable the default benchmark-worker
  benchmark-worker:
    replicas: 0
  # Simulates payment info validation
  validate-payment:
    # Defines the default replica count for this specific worker
    replicas: 1
    # The size of the job queue, i.e. how many jobs can be buffered on this worker without being worked on
    capacity: 30
    # The job type to active and complete
    jobType: "validate-payment-info"
    payloadPath: "bpmn/demo/worker-payload.json"
    # How long to simulate the work, i.e. delay
    completionDelay: 500ms
    # Defines the logging level for this worker
    logLevel: "INFO"
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 500m
        memory: 256Mi
  # Simulates temporary user creation before email verification
  create-user:
    replicas: 1
    capacity: 30
    jobType: "create-unverified-user"
    payloadPath: "bpmn/demo/worker-payload.json"
    completionDelay: 10ms
    logLevel: "INFO"
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 500m
        memory: 256Mi
  # Simulates notifying the user about some failure
  notify-customer:
    replicas: 1
    capacity: 30
    jobType: "notify-customer-failure"
    payloadPath: "bpmn/demo/worker-payload.json"
    completionDelay: 50ms
    logLevel: "INFO"
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 500m
        memory: 256Mi
  # Simulates verifying the email notification
  verify-email:
    replicas: 1
    capacity: 30
    jobType: "send-verification-email"
    payloadPath: "bpmn/demo/worker-payload.json"
    completionDelay: 1s
    message:
      name: "verify-email"
      correlationVariable: "email"
    logLevel: "INFO"
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 500m
        memory: 256Mi
  # Simulates cleaning up unverified users
  cleanup-users:
    replicas: 1
    capacity: 30
    jobType: "clean-unverified-user"
    payloadPath: "bpmn/demo/worker-payload.json"
    completionDelay: 10ms
    logLevel: "INFO"
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 500m
        memory: 256Mi
  # Simulates sending the verification email as a last step
  welcome-email:
    replicas: 1
    capacity: 30
    jobType: "send-welcome-email"
    payloadPath: "bpmn/demo/worker-payload.json"
    completionDelay: 100ms
    logLevel: "INFO"
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 500m
        memory: 256Mi