apiVersion: camunda.sijoma.dev/v1alpha1
kind: ZeebeAutoscaler
metadata:
  name: camunda-platform-zeebe
spec:
  replicas: 3
  zeebeRef:
    # Name of the Zeebe StatefulSet to scale in the same namespace
    name: camunda-platform-zeebe # Default (can be omitted)
    gateway:
      # Name of the Service of the Zeebe Gateway
      serviceName: camunda-platform-zeebe-gateway # Default (can be omitted)
      port: 9600
