global:
  multitenancy:
    enabled: false
  image:
    tag: 8.6.0
    pullPolicy: IfNotPresent
  identity:
    auth:
      enabled: false

zeebe:
  clusterSize: "3"
  partitionCount: "6"
  replicationFactor: "3"
  cpuThreadCount: 6
  ioThreadCount: 6

  image:
    tag: 8.6.0

  javaOpts: >-
    -XX:MaxRAMPercentage=25.0
    -XX:+ExitOnOutOfMemoryError
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/usr/local/zeebe/data
    -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log
    -Xlog:gc*:file=/usr/local/zeebe/data/gc.log:time:filecount=7,filesize=8M

  extraVolumes:
    - name: zeebe-exporters
      emptyDir: {}

  extraVolumeMounts:
    - name: zeebe-exporters
      mountPath: /usr/local/zeebe/exporters

  extraInitContainers:
    - name: job-metric-exporter
      image: ghcr.io/sijoma/camunda-autoscaling-hackday/job-metric-exporter:autoscaling-demo
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: zeebe-exporters
          mountPath: /exporters

  retention:
    enabled: true
    minimumAge: 10m

  env:
    - name: K8S_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: K8S_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: ZEEBE_LOG_APPENDER
      value: Stackdriver
    - name: ZEEBE_LOG_STACKDRIVER_SERVICENAME
      value: zeebe
    - name: ZEEBE_LOG_STACKDRIVER_SERVICEVERSION
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: ATOMIX_LOG_LEVEL
      value: INFO
    - name: ZEEBE_LOG_LEVEL
      value: DEBUG
    - name: ZEEBE_BROKER_EXPORTERS_JOBMETRIC_CLASSNAME
      value: "com.github.sijoma.exporter.JobMetricExporter"
    - name: ZEEBE_BROKER_EXPORTERS_JOBMETRIC_JARPATH
      value: "/usr/local/zeebe/exporters/job-metric-exporter.jar"
    - name: ZEEBE_BROKER_EXPERIMENTAL_ROCKSDB_MEMORYLIMIT
      value: 128MB
    - name: ZEEBE_BROKER_EXECUTIONMETRICSEXPORTERENABLED
      value: "true"
    - name: ZEEBE_BROKER_FLOWCONTROL_WRITE_ENABLED
      value: "true"
    - name: ZEEBE_BROKER_FLOWCONTROL_WRITE_LIMIT
      value: "1000"
    - name: ZEEBE_BROKER_FLOWCONTROL_WRITE_THROTTLING_ENABLED
      value: "true"
    - name: ZEEBE_BROKER_FLOWCONTROL_WRITE_THROTTLING_ACCEPTABLEBACKLOG
      value: "100000"
    - name: ZEEBE_BROKER_FLOWCONTROL_WRITE_THROTTLING_MINIMUMLIMIT
      value: "100"
    - name: ZEEBE_BROKER_FLOWCONTROL_WRITE_THROTTLING_RESOLUTION
      value: "15s"

  resources:
    limits:
      cpu: 1350m
      memory: 4Gi
    requests:
      cpu: 1350m
      memory: 4Gi

  pvcAccessMode: [ "ReadWriteOnce" ]
  pvcSize: 32Gi
  pvcStorageClassName: ssd

  podSecurityContext:
    runAsNonRoot: false
    fsGroup: 0

  containerSecurityContext:
    allowPrivilegeEscalation: true
    privileged: true
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0

zeebeGateway:
  replicas: 2
  logLevel: debug

  image:
    tag: 8.6.0

  env:
    - name: ZEEBE_LOG_APPENDER
      value: Stackdriver
    - name: ZEEBE_LOG_STACKDRIVER_SERVICENAME
      value: zeebe
    - name: ZEEBE_LOG_STACKDRIVER_SERVICEVERSION
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: ATOMIX_LOG_LEVEL
      value: INFO
    - name: ZEEBE_LOG_LEVEL
      value: DEBUG

  resources:
    limits:
      cpu: 450m
      memory: 1Gi
    requests:
      cpu: 450m
      memory: 1Gi

console:
  enabled: false

operate:
  enabled: false

tasklist:
  enabled: false

identity:
  enabled: false

identityKeycloak:
  enabled: false

optimize:
  enabled: false

connectors:
  enabled: false

webModeler:
  enabled: false

postgresql:
  enabled: false

# ELASTIC
elasticsearch:
  enabled: true
  imageTag: 8.9.2

  master:
    fullnameOverride: elastic
    nameOverride: elastic
    replicaCount: 3
    pdb:
      minAvailable: 2
    heapSize: 3g
    resources:
      requests:
        cpu: 1
        memory: 3Gi
      limits:
        cpu: 2
        memory: 6Gi
    persistence:
      storageClass: "ssd"
      size: 16Gi
      accessModes: [ "ReadWriteOnce" ]

prometheusServiceMonitor:
  enabled: true
  labels:
    release: monitoring
  scrapeInterval: 30s

prometheus-elasticsearch-exporter:
  es:
    uri: "http://{{ .Release.Name }}-elasticsearch:9200"
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring