connectors:
  enabled: false

operate:
  enabled: false

optimize:
  enabled: false

tasklist:
  enabled: false

identity:
  enabled: false

identityKeycloak:
  enabled: false

elasticsearch:
  enabled: false

global:
  multitenancy:
    enabled: false
  elasticsearch:
    enabled: false
  identity:
    auth:
      enabled: false

zeebe:
  clusterSize: "3"
  partitionCount: "3"
  replicationFactor: "3"
  # https://hub.docker.com/r/camunda/zeebe/tags
  image:
    tag: 8.5.3

zeebeGateway:
  replicas: 1
  # https://hub.docker.com/r/camunda/zeebe/tags
  image:
    tag: 8.5.3