apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-zeebe-gateway
  namespace: camunda-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: camunda-platform-zeebe-gateway
    kind: Deployment
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
