apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: camunda-platform

resources:
  - namespace.yaml
  - camunda_v1alpha1_zeebeautoscaler.yaml
  - zeebe-svc-monitor.yaml

generators:
  - camunda-chart.yaml
