apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  - namespace.yaml
# Only enable if you have the camunda-scaling-operator installed
  - camunda_v1alpha1_zeebeautoscaler.yaml

generators:
  - camunda-chart.yaml
