apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zeebe-broker-servicemonitor
  labels:
    app.kubernetes.io/app: zeebe
    app.kubernetes.io/component: broker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: zeebe-broker
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      interval: 15s
      path: /actuator/prometheus
