apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: camunda-platform
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
        app.kubernetes.io/component: zeebe-client
    spec:
      containers:
        - name: worker
          image: ghcr.io/npepinpe/camunda-hackday-worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: JDK_JAVA_OPTIONS
              value: >-
                -Dconfig.override_with_env_vars=true
                -Dapp.brokerUrl=camunda-platform-zeebe-gateway:26500
                -Dzeebe.client.requestTimeout=62000
                -Dapp.worker.capacity=60
                -Dapp.worker.pollingDelay=1ms
                -Dapp.worker.completionDelay=50ms
                -XX:+HeapDumpOnOutOfMemoryError
            - name: LOG_LEVEL
              value: "warn"
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 9600
              name: "http"
