---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/scale
  verbs:
  - get
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
- apiGroups:
  - camunda.sijoma.dev
  resources:
  - zeebeautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - camunda.sijoma.dev
  resources:
  - zeebeautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - camunda.sijoma.dev
  resources:
  - zeebeautoscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - camunda.sijoma.dev
  resources:
  - zeebepartitionautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - camunda.sijoma.dev
  resources:
  - zeebepartitionautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - camunda.sijoma.dev
  resources:
  - zeebepartitionautoscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
