/*
Cluster Topology Management API

API for managing cluster membership and partition distribution.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zbmgmt

import (
	"encoding/json"
)

// checks if the ExporterConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExporterConfig{}

// ExporterConfig struct for ExporterConfig
type ExporterConfig struct {
	// The ID of an exporter
	Id    *string            `json:"id,omitempty"`
	State *ExporterStateCode `json:"state,omitempty"`
}

// NewExporterConfig instantiates a new ExporterConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExporterConfig() *ExporterConfig {
	this := ExporterConfig{}
	return &this
}

// NewExporterConfigWithDefaults instantiates a new ExporterConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExporterConfigWithDefaults() *ExporterConfig {
	this := ExporterConfig{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ExporterConfig) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExporterConfig) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ExporterConfig) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ExporterConfig) SetId(v string) {
	o.Id = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ExporterConfig) GetState() ExporterStateCode {
	if o == nil || IsNil(o.State) {
		var ret ExporterStateCode
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExporterConfig) GetStateOk() (*ExporterStateCode, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ExporterConfig) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given ExporterStateCode and assigns it to the State field.
func (o *ExporterConfig) SetState(v ExporterStateCode) {
	o.State = &v
}

func (o ExporterConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExporterConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullableExporterConfig struct {
	value *ExporterConfig
	isSet bool
}

func (v NullableExporterConfig) Get() *ExporterConfig {
	return v.value
}

func (v *NullableExporterConfig) Set(val *ExporterConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableExporterConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableExporterConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExporterConfig(val *ExporterConfig) *NullableExporterConfig {
	return &NullableExporterConfig{value: val, isSet: true}
}

func (v NullableExporterConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExporterConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
