apiVersion: v1
kind: Service
metadata:
  name: clients
  labels:
    release: monitoring
    app.kubernetes.io/component: zeebe-client
spec:
  selector:
    app.kubernetes.io/component: zeebe-client
  ports:
  - name: http
    port: 9600