//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeebeAutoscaler) DeepCopyInto(out *ZeebeAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeebeAutoscaler.
func (in *ZeebeAutoscaler) DeepCopy() *ZeebeAutoscaler {
	if in == nil {
		return nil
	}
	out := new(ZeebeAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZeebeAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeebeAutoscalerList) DeepCopyInto(out *ZeebeAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZeebeAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeebeAutoscalerList.
func (in *ZeebeAutoscalerList) DeepCopy() *ZeebeAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(ZeebeAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZeebeAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeebeAutoscalerSpec) DeepCopyInto(out *ZeebeAutoscalerSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	out.ZeebeRef = in.ZeebeRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeebeAutoscalerSpec.
func (in *ZeebeAutoscalerSpec) DeepCopy() *ZeebeAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(ZeebeAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeebeAutoscalerStatus) DeepCopyInto(out *ZeebeAutoscalerStatus) {
	*out = *in
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeebeAutoscalerStatus.
func (in *ZeebeAutoscalerStatus) DeepCopy() *ZeebeAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(ZeebeAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeebePartitionAutoscaler) DeepCopyInto(out *ZeebePartitionAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeebePartitionAutoscaler.
func (in *ZeebePartitionAutoscaler) DeepCopy() *ZeebePartitionAutoscaler {
	if in == nil {
		return nil
	}
	out := new(ZeebePartitionAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZeebePartitionAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeebePartitionAutoscalerList) DeepCopyInto(out *ZeebePartitionAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZeebePartitionAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeebePartitionAutoscalerList.
func (in *ZeebePartitionAutoscalerList) DeepCopy() *ZeebePartitionAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(ZeebePartitionAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZeebePartitionAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeebePartitionAutoscalerSpec) DeepCopyInto(out *ZeebePartitionAutoscalerSpec) {
	*out = *in
	if in.PartitionCount != nil {
		in, out := &in.PartitionCount, &out.PartitionCount
		*out = new(int32)
		**out = **in
	}
	if in.ReplicationFactor != nil {
		in, out := &in.ReplicationFactor, &out.ReplicationFactor
		*out = new(int32)
		**out = **in
	}
	if in.MaxPartitionPerBroker != nil {
		in, out := &in.MaxPartitionPerBroker, &out.MaxPartitionPerBroker
		*out = new(int32)
		**out = **in
	}
	out.ZeebeRef = in.ZeebeRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeebePartitionAutoscalerSpec.
func (in *ZeebePartitionAutoscalerSpec) DeepCopy() *ZeebePartitionAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(ZeebePartitionAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeebePartitionAutoscalerStatus) DeepCopyInto(out *ZeebePartitionAutoscalerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeebePartitionAutoscalerStatus.
func (in *ZeebePartitionAutoscalerStatus) DeepCopy() *ZeebePartitionAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(ZeebePartitionAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeebeRef) DeepCopyInto(out *ZeebeRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeebeRef.
func (in *ZeebeRef) DeepCopy() *ZeebeRef {
	if in == nil {
		return nil
	}
	out := new(ZeebeRef)
	in.DeepCopyInto(out)
	return out
}
