apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  camunda-cloud/owned-by-repo: camunda-cloud/camunda-operator

resources:
- ../../config/default

patches:
- path: manager-patch.yaml
images:
- name: controller
  newName: controller
  newTag: latest
